#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL with parameters uncertainties
#
# @type Quadrotor Wide
#
# @maintainer Salvatore Marcellini <salvatore.marcellini@unina.it>
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

#Here we put the nominal values

param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.1515
param set-default CA_ROTOR0_PY 0.245
param set-default CA_ROTOR0_KM 0.06
param set-default CA_ROTOR0_CT 0.000584

param set-default CA_ROTOR1_PX -0.1515
param set-default CA_ROTOR1_PY -0.1875
param set-default CA_ROTOR1_KM 0.06
param set-default CA_ROTOR1_CT 0.000584

param set-default CA_ROTOR2_PX 0.1515
param set-default CA_ROTOR2_PY -0.245
param set-default CA_ROTOR2_KM -0.06
param set-default CA_ROTOR2_CT 0.000584

param set-default CA_ROTOR3_PX -0.1515
param set-default CA_ROTOR3_PY 0.1875
param set-default CA_ROTOR3_KM -0.06
param set-default CA_ROTOR3_CT 0.000584

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104